<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.10" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="chassis_height" value="0.05" />
  <xacro:property name="chassis_width" value="0.15" />
  <xacro:property name="chassis_length" value="0.4" />
  

  <xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo" />
  <xacro:object_controller/>

  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name="chassis">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="5"/>
      <inertia ixx="${(5/12) * (chassis_width * chassis_width + chassis_height* chassis_height)}" ixy="0" ixz="0" iyy="${(5/12) * (chassis_length * chassis_length + chassis_height * chassis_height)}" iyz="0" izz="${(5/12) * (chassis_width * chassis_width + chassis_length * chassis_length)}" />
    </inertial>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Purple</material>
  </gazebo>

  <xacro:macro name="wheel_link" params="name radius width mass">
    <gazebo reference="${name}">
      <material>Gazebo/Black</material>
      <mu1>0.84</mu1>
      <mu2>0.84</mu2>
    </gazebo>

    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
      </visual>

      <collision>
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * (3 * radius * radius + width * width)}" ixy="0" ixz="0" iyy="${(1/12) * mass * (3 * radius * radius + width * width)}" iyz="0" izz="${(1/2) * mass * radius * radius}"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:wheel_link name="wFL" radius="${wheel_radius}" width="${wheel_width}" mass="0.3"/>

  <joint name="jFL" type="continuous">
    <parent link="chassis"/>
    <child link="wFL"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${chassis_length/2 - 0.03} ${chassis_width/2 + wheel_width/2} 0" rpy="${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <xacro:wheel_link name="wBL" radius="${wheel_radius}" width="${wheel_width}" mass="0.3"/>

  <joint name="jBL" type="continuous">
    <parent link="chassis"/>
    <child link="wBL"/>
    <axis xyz="0 0 1"/>
    <origin xyz="-${chassis_length/2 - 0.03} ${chassis_width/2 + wheel_width/2} 0" rpy="${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <xacro:wheel_link name="wFR" radius="${wheel_radius}" width="${wheel_width}" mass="0.3"/>

  <joint name="jFR" type="continuous">
    <parent link="chassis"/>
    <child link="wFR"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${chassis_length/2 - 0.03} -${chassis_width/2 + wheel_width/2} 0" rpy="${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <xacro:wheel_link name="wBR" radius="${wheel_radius}" width="${wheel_width}" mass="0.3"/>

  <joint name="jBR" type="continuous">
    <parent link="chassis"/>
    <child link="wBR"/>
    <axis xyz="0 0 1"/>
    <origin xyz="-${chassis_length/2 - 0.03} -${chassis_width/2 + wheel_width/2} 0" rpy="${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <link name='camera'>
     <pose> 0 0 0 0 0 0</pose>

     <inertial>
       <mass value="0.1"/>
       <origin xyz="0.0 0 0" rpy="0.0 0 0"/>
       <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
       />
     </inertial>

     <collision name='collision'>
       <origin xyz="0 0 0" rpy=" 0 0 0"/>
       <geometry>
          <box size="0.05 0.05 0.05"/>
       </geometry>
     </collision>

     <visual name='camera_visual'>
       <origin xyz="0 0 0" rpy="0 0 0"/>
       <geometry>
          <box size="0.05 0.05 0.05"/>
       </geometry>
     </visual>
  </link>

  <gazebo reference="camera">
    <material>Gazebo/Black</material>
  </gazebo>
 

  <joint type="fixed" name="camera_joint">
    <origin xyz="0.2 0 0" rpy="0 0 0"/>
    <child link="camera"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  
  <link name='hokuyo'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="1e-5"/>
      <origin xyz="0.0 0 0" rpy="0.0 0 0"/>
      <inertia
          ixx="1e-6" ixy="0" ixz="0"
          iyy="1e-6" iyz="0"
          izz="1e-6"
      />
    </inertial>

    <collision name='collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/> 
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry>
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
    </visual>
  </link>

  <joint type="fixed" name="hokuyo_joint">
    <origin xyz="0.15 0.0 0.1" rpy="0 0 0"/>
    <child link="hokuyo"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
    
</robot>
